### PR TITLE
string library:Supplemental functions added

### PR DESCRIPTION
**Pull request by erkinalp**
strcnt() and strlnlen() taken out of cowsay.

### CODE REVIEW

**Comment by EtchedPixels** [comment]
On Sun, 19 Apr 2015 03:11:05 -0700
Erkin Alp Güney <notifications@github.com> wrote:

> strcnt() and strlnlen() taken out of cowsay.
> You can view, comment on, or merge this pull request online at:
> 

For C library they need to be LGPL or similar (Maciej's file is but your
bit seems to be GPL v2).

Alan

**Comment by erkinalp** [comment]
So separate library.

**Comment by erkinalp** [comment]
It is actually a library for cowsay itself but made available for all GPLv2 applications.

**Comment by erkinalp** [comment]
>cowsay itself
One I have implemented for FUZIX in C, but not the original one

**Comment by erkinalp** [comment]
Now licence changed to LGPL v2.1 or 3 on the user's discretion. LGPLv2.1 will be selected automatically because of licence compatibility issues on this project.

**Comment by erkinalp** [comment]
Chief maintainer says:
>For C library they need to be LGPL or >similar (Maciej's file is but your
>bit seems to be GPL v2).

Done.

**Comment by erkinalp** [comment]
@EtchedPixels: Rebased and ready to merge.

**Comment by erkinalp** [comment]
@EtchedPixels: Rebased and ready to merge now. strlnlen() and strcnt() are useful for typesetting situations, you already know strfry() :ok:

**Comment by erkinalp** [comment]
Ready for merging now.

**Pull request closed without merging**
