### PR TITLE
Readline added

### PR DESCRIPTION
**Pull request by erkinalp**
#204 plus fix for nonovercommit malloc().

### CODE REVIEW

**Comment by Zardoz89** [comment]
I have curiosity. From were comes these idiom to do memset/memcpy to do dependency-break ? I can't find anything about it. 

Also, check this : https://github.com/Zardoz89/readline

**Comment by erkinalp** [comment]
@Zardoz89: It is not a C idiom, it is a hardware-level idiom. Some CPU architectures like AMD64 have superscalar schedulers. You break the dependency into previous access of that memory location if you zero it. The CPU scheduler continues to dispatch your operations in respect to previous values if you do not zero them. It is a pessimization on non-pipelined non-superscalar architectures.

**Comment by Zardoz89** [comment]
Also, you know that they are self-depracting the library ? 
https://github.com/clibs/readline/pull/2#issuecomment-110528928
https://github.com/clibs/clib/issues/21#issuecomment-33294863

**Comment by EtchedPixels** [comment]
Most modern processors are way smarter than to need the memset() trick, also good compilers and C libraries should deal with it for you.

**Pull request closed without merging**
