### PR TITLE
new JeeRetro build

### PR DESCRIPTION
**Pull request by jcw**
Please consider adding this "platform-jeeretro" subdirectory to the FUZIX project. It's meant for use with the Z80 emulator at <https://git.jeelabs.org/jcw/retro/src/branch/master/black407-z80ex>.

See issues #699 and #700 for relevant discussions and fixes that led to this port.

There's still an issue when running on an STM32F407 µC, but the port builds and works in MacOS and Linux. It's now set to use only 2 user banks so it will also fit in 184 KB RAM on the F407.

### CODE REVIEW

**Comment by EtchedPixels** [comment]
Can you clean up the README to reference your platform and perhaps a URL link to the I/O port model it uses. Maybe grep the code for z80pack and fix the other references as appropriate.

Also I can't help thinking it would be nicer if the max ram was not hard coded but an in() reported max banks ?

Otherwise looks good - would be nice to know why are doing the stuff you are with the tty read (in and write to tmpReg), if you are getting a miscompile there with sdcc 3.9.0-rc that's a nasty and one that ought to go to Philipp to get nailed before release.

**Comment by jcw** [comment]
Ok, will do. I don't like the I/O model for system calls, but inherited it from the z80emu example. Have been considering switching to "HALT + .db XYZ", but that will run away the moment an app uses HALT. The cleanest way would perhaps be to "virtualise" all I/O and HALT, and maybe also DI/EI/RETI/RETN.

Yes, hard-coded banking is messy, and may cause problems later. The tty read stuff is just me hacking my way through to get things going. I'm pretty sure I can clean it up a bit, now that it's working.

BTW, the reason I'm doing this is because the z80emu project was a nice / small / clean starting point, which works nicely on a range of µC's. The F407 has 192K ram, hence this attempt to port FUZIX to it. There's overlap with the RC2014 emulator, evidently.

**Comment by jcw** [comment]
Re tty read w/ tmpReg: ah, yes, that's because I don't know the SDCC conventions, i.e. how to pass args in and out of an __asm block. I didn't want to move these routines to a .s file - or should I?

**Comment by EtchedPixels** [comment]
SDCC does this in a kind of weird 8051ish way

__sfr __at 0x01 foo;

then x = foo generates an in

It would have been far better if it was pointer based as you can't do maths on it nicely.

The lowlevel-z80 runtime also provides in() and out() as function calls for the other cases.

**Comment by EtchedPixels** [comment]
Merged.

I will push a few other trivial things (several of which I need to also push for z80pack!)

**Pull request merged**
