### PR TITLE
getline() and getdelim() added

### PR DESCRIPTION
**Pull request by erkinalp**
Character delimited input routines.

### CODE REVIEW

**Comment by erkinalp** [comment]
Look at f6d1c1d.

**Comment by erkinalp** [comment]
Alan: I got it. Unbalanced parens. Will fix it tonight.

**Comment by erkinalp** [comment]
Alan: Try it now. Previously no linkage specified, so not compilable as a library. Now I have marked them `extern`.

**Comment by erkinalp** [comment]
Now ready.

**Comment by erkinalp** [comment]
Re-made commits with slightly different semantics.

**Comment by EtchedPixels** [comment]
Closing. I've pointed out several times you are posting stuff that hasn't been tested, and cannot possibly work.

**Pull request closed without merging**
