### PR TITLE
Make USB uart separate from hardware UART

### PR DESCRIPTION
**Pull request by veremenko-y**
Also make hardware UART fully blocking for kput/kprintf

### CODE REVIEW

**Comment by EtchedPixels** [comment]
-extern uint8_t progbase[USERMEM];
+extern char progbase[USERMEM];

This seems to be unrelated and strange ?

Rest looks ok but please try and use (void) not () for no arg functions. The PI compiler doesn't care but no some targets there is a difference between "no arguments" and "K&R style who knows arguments"

**Comment by veremenko-y** [comment]
> Rest looks ok but please try and use (void) not () for no arg functions. The PI compiler doesn't care but no some targets there is a difference between "no arguments" and "K&R style who knows arguments"

Ack. I'll go though the patch to ensure it doesn't happen again. Do you want me to add this to the CodingStyle.md? (which I realized I haven't read, but it does missing the `foo(void)`).

> This seems to be unrelated and strange ?

This was part of fighting the compiler and conflicting types. I'll check this first and remove if unnecessary.

**Comment by veremenko-y** [comment]
Both issues should be addressed now.

**Comment by EtchedPixels** [comment]
Thanks - merged

**Pull request merged**
