### PR TITLE
Modifications to sh, all platforms: support for comments, add man-page, fix some build warnings, tweak package files

### PR DESCRIPTION
**Pull request by nealcrook**
(ignore the Nov 21 commits below referring to BCPL; I reverted them on Nov 22)

Fixed a set of no-brainer build warnings in sh (6809 binary was identical after these changes).

Added support for comments to sh - code taken from heirloom-sh (http://heirloom.sourceforge.net/index.html). Affects single source file word.c

Added sh.1 manpage taken from archival V7 distribution, tweaked to add reference to # 

Added man page to package file. Added '[' as a hard link to 'test' in the appropriate package file.

I have NOT changed the copyright attributions in word.c to accommodate the code taken from heirloom-sh. The code taken is a single paragraph:

````
+	while (1)
+	{
+		while (c = nextc(0), space(c))		/* skipc() */
+			;
+
+		if (c == COMCHAR)
+		{
+			while ((c = readc()) != NL && c != EOF);
+			peekc = c;
+		}
+		else
+		{
+			break;	/* out of comment - white space loop */
+		}
+	}
````

Strictly, I should bolt in a big boilerplate from heirloom-sh and add or at least reference the files CALDERA.LICENSE and OPENSOLARIS.LICENSE

Opinions?

### CODE REVIEW

**Comment by beretta42** [comment]
It works for me.  Much less compiler errors too.

**Comment by nealcrook** [comment]
good. Thanks, Brett.. one step closer to the 21st century.

**Comment by EtchedPixels** [comment]
The Caldera copyright is already in the COPYRIGHT file for the V7 directory, along with Robert Nordier and the BSD bits. Can you add the OPENSOLARIS.LICENSE to that file. I'm sure we'll borrow other Heirloom bits in future!

**Comment by nealcrook** [comment]
>> Can you add the OPENSOLARIS.LICENSE to that file.

Done.

>> I'm sure we'll borrow other Heirloom bits in future!

Agreed. I already have my eye on "oawk" having spent a "happy" few hours failing to get a v7_addendum codebase to compile (first step is to get an old FLEX to run. I failed)

**Pull request merged**
