### PR TITLE
Use precompiled sdcc for Travis builds

### PR DESCRIPTION
**Pull request by davidgiven**
Rather than downloading and building sdcc ourselves, use the precompiled version in my PPA. This reduces build time from about 8 minutes to about 5.

### CODE REVIEW

**Comment by erkinalp** [comment]
Travis CI seems inactive on EtchedPixels.

**Comment by davidgiven** [comment]
Yes, it's not set up there yet (it's not my repository so I can't set it up). But it's trivial to set up for your own, which means it'll do automatic test builds before sending off pull requests. Just log in to travis-ci, refresh your repositories, and switch your Fuzix project to 'on'.

**Comment by erkinalp** [comment]
Do I have to pay for it?

**Comment by Zardoz89** [comment]
It's free. But the owner (user or team member) of the github repository is who can activate it agains the github repo. In other words @EtchedPixels  .
We use it on Trillek and it's really a great tool to see if something gets broken on a possible merge.

**Comment by EtchedPixels** [comment]
I'm waiting for it all to settle down somewhat first, and for some of the problem cases to be dealt with (eg you need sdcc 3.4.2 or higher to build a valid kernel for some platforms, and I don't think 3.4.0 builds all the user space validly either).

I'm hoping the pending 3.5.0 has everything we need in it and works nicely.

**Comment by Zardoz89** [comment]
At least these travis file give us a basic recipe how to build fuzix

**Comment by erkinalp** [comment]
We still have minutes to half an hour build files. We should have better seconds of incremental builds before continuous integration.

**Comment by EtchedPixels** [comment]
sdcc is very slow so that isn't going to happen

**Comment by erkinalp** [comment]
Then transistion into a faster compiler. Do we have a target where SDCC is the only existing C compiler?

**Comment by EtchedPixels** [comment]
There is no remotely comparable Z80/Z180 compiler.

**Comment by erkinalp** [comment]
> remotely comparable

What aspect? Speed? Optimisation?

**Comment by Zardoz89** [comment]
z88dk ?

**Comment by EtchedPixels** [comment]
botth - and no z88dk isn't even in the running. Plus z88dk is slowly moving towards using sdcc.

**Pull request merged**
