### PR TITLE
syscall_net: release closed socket to avoid running out of free sockets

### PR DESCRIPTION
**Pull request by pawosm-arm**
This solves a huge problem with userspace network related programs
that could be started only once, as any subsequent run was not
possible due to the lack of free sockets.

### CODE REVIEW

**Comment by pawosm-arm** [comment]
To reviewers: please share your opinion on possible data race on sockdata[i].socket between netproto_socket() and netproto_free()

**Comment by pawosm-arm** [comment]
NB: I've added some basic protection of the disputed variable.

**Comment by EtchedPixels** [comment]
This looks a bit odd to me - the userspace close of a socket doesn't mean the resources are free (consider stuff like TCP time wait). Unless I'm missing something this should be happening when the protocol module decides the socket is no longer relevant. Hence the comment.

**Comment by pawosm-arm** [comment]
There must be something missing then. netproto_free() is only called from net_free() which in normal course of program execution is nowhere to be called. In effect, sockdata[i].socket (which links socket to socketdata) remains non-NULL even long after the process which assigned it is long gone. Very quickly netproto_socket() can't find free slots in sockdata[] array and no more sockets can be created.
Maybe syscall_net.c is not the right place to nullify this and netproto_free should be called from netproto_close()?

**Comment by pawosm-arm** [comment]
Also, as I added call to `netproto_free(s)` to `case NE_UNHOOK:` in `netdev_write()`, it didn't help. Something more is missing.

**Comment by pawosm-arm** [comment]
@EtchedPixels I've just pushed a new candidate, please take a look.

**Pull request merged**
