### PR TITLE
6809: compile libs separately

### PR DESCRIPTION
**Pull request by beretta42**
This matches what is being done on the z80 makefiles.

### CODE REVIEW

**Comment by nealcrook** [comment]
Hoorah. I wondered who would crack first and do this!
I also have the stdlib.h mod. in my merge request.
Did this fix your levee build contention? I am hacking in levee right now, and have disambiguated the calls that conflict with standard library stuff. Now working through some other issues to get it to work cleanly on my platform

**Comment by beretta42** [comment]
It definitely helps levee compile, but I think I still need to compile it
with "-O0".  The only other mod I do is increase the buffer size to 8192,
for editing a few bigger files.

Hmm.. if you're patch does the same labs() fix, I wonder if git will merge
mine?  Oh well.. It's not hard to cherry-pick a new PR if needs be.

Maybe try my patch and see if it works OK for you?  I'm absolutely abysmal
at noodling with makefiles.

-Brett

**Comment by nealcrook** [comment]
Hi Brett,
I copied your makefile changes to my messing-with-levee branch and they make things work much, much better. I now have a vanilla "ANSI" build running more-or-less OK. A couple of questions on your levee experience though:

1/ when you start up levee, do you get a startup banner: version and author? I suspect not. It gets written to line 1 then immediately overwritten.

2/ can you edit an existing file, or read a file into an existing buffer? For me I always get a message that the file size is "-1 bytes" which looks like an untested "fail".

3/ do you get any weirdness with screen redraws? I get whole unused lines filled with "~" (instead of
just a single ~ in the first column)

I am part-way through converting lv.doc to a man page (helped by grabbing the man page from the latest version of levee)

I also spotted that the levee command jump-table is 256 bytes but it can be 128 bytes (forbid top-bit set) for an instant saving of 128 bytes.

**Comment by beretta42** [comment]
On Jul 13, 2016 4:48 PM, "Neal Crook" <notifications@github.com> wrote:
>
> 1/ when you start up levee, do you get a startup banner: version and
author? I suspect not. It gets written to line 1 then immediately
overwritten.

Yes Sir. Coco3 does same. (Some while ago it would pop up on bottom line.)

>
> 2/ can you edit an existing file, or read a file into an existing buffer?
For me I always get a message that the file size is "-1 bytes" which looks
like an untested "fail".

definitely had this error - i think compiling with "-O0"  fixes this.

>
> 3/ do you get any weirdness with screen redraws? I get whole unused lines
filled with "~" (instead of
> just a single ~ in the first column)

Nope.. I dont get that.

> I am part-way through converting lv.doc to a man page (helped by grabbing
the man page from the latest version of levee)
>
> I also spotted that the levee command jump-table is 256 bytes but it can
be 128 bytes (forbid top-bit set) for an instant saving of 128 bytes.

**Pull request merged**
