### PR TITLE
dd: a fix and a feature

### PR DESCRIPTION
**Pull request by erkinalp**
Now initializing locals statically at declarator, therefore saving initialization code. Also strfry=NNN option added which displaces data within given block.

### CODE REVIEW

**Comment by EtchedPixels** [comment]
Saves no code at all. The compiler will generate the same code for both for auto variables.

And we don't need silly options on a small machine.

**Comment by erkinalp** [comment]
Will staticify the initialized variables and re-make the PR. OtOH, strfry=nnn is a useful secure removal tool in the situations if you are allowed to owerwrite a file with garbage data but not securely erase it. Shuffle as a proxy for erase.

**Comment by EtchedPixels** [comment]
overwriting a file doesn't erase it on a lot of media types and you could just as well overwrite it using yes and dd, plus anyone using Fuzix on an 8bit micro for secure activities is crazy,

**Comment by erkinalp** [comment]
> doesn't erase it on a lot of media types

It does in those Unix is originally intended for, i.e. Floppy, tape, HDD, puncher, line printer.

> using Fuzix on an 8bit micro for secure activities is crazy

FUZIX does have 16/32 bit targets too, those are usable in embedded applications. Not all FUZIX targets are vintage 8-bit resurrecters.

**Comment by EtchedPixels** [comment]
Floppy needs a bulk eraser or the right patterns and  lot of care. Tapes need to be bulk erased or via an erase head. Hard disks do block reassignment so cannot safely be erased this way. Modern ones have special commands for it. Punched paper tape is erased by putting it in a shredder and line printer output likewise.

So it's not actually any use.

**Pull request closed without merging**
