### PR TITLE
levee cleanup, and various other app tweaks and tidies

### PR DESCRIPTION
**Pull request by nealcrook**
I had this levee work in progress from early in the summer but got diverted on the compiler bug and a multicomp VDU hardware bug. All fixed now so I pulled it all back together.
Changes elsewhere are cosmetic.

### CODE REVIEW

**Comment by nealcrook** [comment]
sorry, a bunch of my makefile fixes match a merge you did already.

**Comment by tormodvolden** [comment]
Not a big problem, but (in general!) it would be nice if the commit message header mentioned what part/application/platform/etc are affected. Makes it easier for casual (re)viewers to glance through the commit list without having to open each of them to look for bits of special interest. You know with the flood of FUZIX changes we get all the time :)

**Comment by nealcrook** [comment]
> nice if the commit message header mentioned what part/application/platform/etc are affected

Good point. I will try to comply in the future.

**Comment by nealcrook** [comment]
Hi Alan,
do you need me to resolve those conflicts or will you take care of it (basically, where I change include path from 6502 to 6809 and you'd already committed a pull that did it)

**Comment by EtchedPixels** [comment]
If you could sort it that would be best

**Comment by tormodvolden** [comment]
"git rebase" is undervalued :) If you rebase your branch on top of current master, the obsolete parts get cleaned out (in most cases without fuzz, in the worst case git rebase --abort is your friend).

**Comment by nealcrook** [comment]
OK it's all clean now. (I did use "git rebase" once and it was a Great Learning Experience. Fortunately, the conflicts here mostly only required reverting a single commit)
OTOH, the commit that I conflicted with makes changes that prevent Fuzix from compiling with the Tormod's tools. See bug report..

**Comment by nealcrook** [comment]
Tormod: please see and express opinion on issue #457 
What is the Right Way to use /Build/tools/m6809-* ??
thanks

**Pull request merged**
