### PR TITLE
Ask old password when root is changing its own password

### PR DESCRIPTION
**Pull request by erkinalp**

### CODE REVIEW

**Comment by willsowerbutts** [comment]
How is root supposed to change their password when they forget it?

**Comment by erkinalp** [comment]
By deleting its password from /etc/passwd directly.

**Comment by willsowerbutts** [comment]
So, if root can just change /etc/passwd directly, what does this change achieve?

**Comment by erkinalp** [comment]
Discouraging root to forget its password. Anyway, these small boxes are pseudo-multiuser at most :)

**Comment by willsowerbutts** [comment]
It's more of a roadblock than discouragement :) I would prefer to stick with the tradition (root is never prompted for the current password)

By the way, thank you for your work on porting a better shell. Something with globbing, pipelines and redirection would be great.

**Comment by EtchedPixels** [comment]
The existing behaviour is traditional so should IMHO be kept

**Pull request closed without merging**
