### PR TITLE
Added port for Amstrad CPC6128

### PR DESCRIPTION
**Pull request by ajcasado**

### CODE REVIEW

**Comment by EtchedPixels** [comment]
Thanks , will take a look next week

**Comment by poliander** [comment]
[Confirmed working](https://www.cpcwiki.eu/forum/applications/port-of-fuzix-for-the-cpc6128/msg243888/#msg243888) on a real CPC 6128

**Comment by EtchedPixels** [comment]
Very cool.

**Comment by EtchedPixels** [comment]
Missing fuzix.lnk ?

**Comment by ajcasado** [comment]
Yes, it was missing. I've uploaded it and made a pull request

**Pull request merged**
