### PR TITLE
Single user mode added

### PR DESCRIPTION
**Pull request by erkinalp**
Differences with muiti-user build include:
* Always root
* No password asked at login
* Dummy setuid,setgid

Single-user build may be useful for limited ROM situations as some utilities will not be needed such as `passwd`, `adduser`, `deluser`, `chown`, `chgrp`.

### CODE REVIEW

**Comment by EtchedPixels** [comment]
I don't understand why you need any kernel changes for this. You start off as root/root so they can simply be omitted.

The init bit maybe makes sense but could also be automated. Eg if before the putstr("login:") you did

pwd = getpwnam(root);
if (!pwd->pw-passwd[0])
     spawn(pwd);
else {
  putstr("login: ")

etc...

I'd rather avoid ifdefs

**Comment by erkinalp** [comment]
Its purpose is to have an _inherently single-user_ build as opposed to an optional single-user boot mode. This is the reason for kernel patch.

**Comment by EtchedPixels** [comment]
Why do I want one ? It serves no useful purpose

**Comment by erkinalp** [comment]
Some space can be saved with utilities left out in a single-user build.

**Comment by EtchedPixels** [comment]
You can leave them out anyway..

**Comment by erkinalp** [comment]
Closing upon maintainer's request. Forks may make use of it.

**Pull request closed without merging**
