### PR TITLE
V68 softmmu support

### PR DESCRIPTION
**Pull request by piso77**
-Update the page_remalloc() API
-Fix u_data copying in dofork
-Misc other fixes
-Hook the target to Travis

While here, fix the z80 build

### CODE REVIEW

**Comment by EtchedPixels** [comment]
I fixed the z80 build by pushing the new tool I forgot to.

The flat_mem/softmmu etc stuff needs a lot of work - the platform tree for that and for banked is very much a WIP. The only 68K port I made work so far as the simple one process at a time setup, so I could get the kernel 32bit clean and build/test it with a userspace.

**Comment by piso77** [comment]
Ok, then let's leave it out.

One question: to test the 68k target, which emulator did you use? Or did you test it on real hardware?

**Comment by EtchedPixels** [comment]
https://github.com/EtchedPixels/Virtual68

It's a completely minimal emulator for simple debug. I've been pondering adding Motorola 68681 support to it, as it would then emulate the Tiny68K board

https://www.retrobrewcomputers.org/doku.php?id=boards:sbc:tiny68k:tiny68k_rev2

which is I have sitting here waiting for me to work on.

**Comment by piso77** [comment]
Ok, i built Virtual68 and IDE, built the "Hello world" thing and it worked.

Then, since i didn't know how to package a disk.img, i tried the prebuilt image from here:

http://www.fuzix.org/downloads/v68.tar.gz

replaced boot.dat and disk.img and:

flag@harukaze:~/Virtual68$ ./v68 -p
V68 Boot Services
Revision 0.1 Alpha

Clearing memory
41e: BUS 524288
41e: BUS 524289
41e: BUS 524290
41e: BUS 524291
424: BUS 524288
424: BUS 524289
424: BUS 524290
424: BUS 524291
ide0: ACME NEMESIS RIDICULII v0.1
ide1: not present
> b
Booting from IDE disk 0
OK
Loading...OK
FUZIX version 0.1
Copyright (c) 1988-2002 by H.F.Bower, D.Braun, S.Nitschke, H.Peraza
Copyright (c) 1997-2001 by Arcady Schekochikhin, Adriano C. R. da Cunha
Copyright (c) 2013-2015 Will Sowerbutts <will@sowerbutts.com>
Copyright (c) 2014-2015 Alan Cox <alan@etchedpixels.co.uk>
Devboot
512kB total RAM, 448kB available to processes (15 processes max)
Enabling interrupts ... ok.
IDE reset
IDE drive 0: hda: hda1 hda2 
IDE drive 1: ide error, status=0000
bootdev: 

but i was stuck there - after reading Kernel/start.c::bootdevice(), i blindly tried some numeric value until i hit '2' and i got the root prompt:

bootdev: 2
Mounting root fs (root_dev=2, rw): OK
Starting /init
init version 0.9.0ac#1
# 

tried a couple of binaries in /bin and they worked fine (except for ps that was complaning about a kernel / userspace mismatch).

Now, how do i pack my fs? Kernel + user space i mean.

**Comment by piso77** [comment]
Uhm, i found the Standalone/filesystem-src/* tools, but it's giving me several errors:

```
$ ./build-filesystem test.img 256 65535
Found package mini
Found package basefs
Found package ccp
Found package BCPL
Found package adventure
Found package MWC-cmd
Found package ld09
Found package drivewire
Found package netd-base
Found package netd-lwwire
Found package netd-coconic
Found package dasm09
Found package games
Found package V7-cmd
Found package V7-cmd-man
Found package V7-sh
Found package V7-sh-man
Found package V7-games
Found package V7-games-man
Found package fview
Found package cursesgames
Found package as09
Found package SmallC
Found package TCL
Found package levee-vt52
Found package levee-ansi
Found package levee-termcap
Found package rpilot
Found package ue
Found package flashrom
Found package fforth
Found package util-mini
Found package util
Resolving package mini: enabled=0
Resolving package basefs: enabled=1
Resolving package ccp: enabled=0
Resolving package BCPL: enabled=0
Resolving package adventure: enabled=1
Resolving package MWC-cmd: enabled=1
Resolving package ld09: enabled=1
Resolving package drivewire: enabled=0
Resolving package netd-base: enabled=1
Resolving package netd-lwwire: enabled=0
Resolving package netd-coconic: enabled=0
Resolving package dasm09: enabled=0
Resolving package games: enabled=1
Resolving package V7-cmd: enabled=1
Resolving package V7-cmd-man: enabled=1
Resolving package V7-sh: enabled=1
Resolving package V7-sh-man: enabled=1
Resolving package V7-games: enabled=1
Resolving package V7-games-man: enabled=1
Resolving package fview: enabled=0
Resolving package cursesgames: enabled=1
Resolving package as09: enabled=1
Resolving package SmallC: enabled=1
Resolving package TCL: enabled=0
Resolving package levee-vt52: enabled=0
Resolving package levee-ansi: enabled=0
Resolving package levee-termcap: enabled=0
Resolving package rpilot: enabled=0
Resolving package ue: enabled=1
Resolving package flashrom: enabled=1
Resolving package fforth: enabled=1
Resolving package util-mini: enabled=1
Resolving package util: enabled=1
Processing package basefs
Processing package adventure
Processing package MWC-cmd
ERROR du:10 file not found
Processing package ld09
Processing package netd-base
Processing package games
ERROR advint:19 file not found
Processing package V7-cmd
ERROR ed:18 file not found
Processing package V7-cmd-man
Processing package V7-sh
Processing package V7-sh-man
Processing package V7-games
Processing package V7-games-man
Processing package cursesgames
Processing package as09
Processing package SmallC
Processing package ue
Processing package flashrom
Processing package fforth
Processing package util-mini
Processing package util
ERROR gptparse:71 file not found
ERROR seq:91 file not found
ERROR Fix errors and re-run
```
and i don't see any reference to the kernel, i wonder if there's another step involved after this.

**Comment by EtchedPixels** [comment]
The kernel is currently written separately onto the disk (writing a nice bootloader is one of those 'must do one day' jobs.

See the install-fs and install-fuzix scripts

**Pull request closed without merging**
